server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    server-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false # 是否注册自己的信息到EurekaServer
    fetch-registry: false # 是否拉取其它服务的信息
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 1000 # 扫描失败服务的间隔时间